language: scala
scala:
  - 2.9.3
  - 2.10.4
  - 2.11.0
jdk:
  - openjdk7
  - oraclejdk7
script:
  - sh -c 'cd snacker' && "sbt -Dlog4j.configuration=file://$TRAVIS_BUILD_DIR/project/travis-log4j.properties ++$TRAVIS_SCALA_VERSION test"

