* Introducció

#+LATEX: \epigraph{«\itshape{[...] el militar barceloní Joan Terré, alcaid de Bellver de Cerdanya, autor d'una dotzena de composicions poètiques en català, entre les quals destaca el poema dedicat} \normalfont{A un meravellós somni i al desengany del món} [...]»}{\citep[253]{Solervicens2016}}

En l'imaginari públic el Barroc català sempre s'ha vist eclipsat per altres períodes literaris. Aquesta ha sigut una de les conseqüències de l'etiqueta /Decadència/ que durant tant de temps ha sobrevolat uns tres cents anys d'història de la literatura catalana. Una etiqueta impròpia dels estudis literaris, i que d'ençà uns anys sembla que comença a entendre's com un error que s'ha comès envers a centenars d'autors. El procés de normalització envers aquest període literari ha sigut una tasca monumental que precedeix el present treball, i de la qual n'és deutor. No obstant això, encara queden molts autors guardats en manuscrits.

Un d'aquests autors és Joan Terrer, un militar barceloní que va exercir com a alcaid[fn:1] del castell de Bellver de Cerdanya. Abans de la redacció d'aquest treball només s'havia fet l'edició de tres poemes seus[fn:2] i, de fet, la cita que encapçala aquesta introducció és tot el que s'indica sobre Terrer a citet:Solervicens2016. L'estat de la qüestió per a aquest autor és, per tant, força minsa, i deixa un buit en els estudis de la literatura catalana del Barroc que aquest treball pretén omplir.

Havent vist això, aquest treball es planteja com a objectiu principal confeccionar una edició crítica de tota la poesia de Joan Terrer. Per tal de fer això s'ha fet una recerca exhaustiva de tots aquells poemes que tenen qualsevol vinculació amb l'autor en qüestió, i s'ha escatit l'autoria per a cadascun d'ells. Finalment, s'ha procedit a la transcripció dels textos i la seva final edició crítica. Durant tot aquest procés s'han seguit els mètodes propis de l'edició crítica i, més concretament, el denominat mètode de Lachmann. A més a més, aquest treball també s'ha posat com a objectiu investigar més en la vida d'aquest autor, per tal de tenir un enteniment més global d'aquest personatge. Tot plegat, aquest treball pretén ser un gra de sorra més en el coneixement que es té de la literatura catalana del Barroc, i pot servir de base per a futurs treballs i materials divulgatius.

Finalment, l'estructura d'aquest document gira al voltant dels objectius suara esmentats. Primer de tot, aquest treball es veu contextualitzat mitjançant dos capítols que tracten la situació històrica i literària en què va viure Terrer. Seguidament, el treball tracta els seus dos objectius principals directament, centrant-se primer en la recerca biogràfica de l'autor, i fent un estudi crític de l'obra de Terrer posteriorment, tot establint els criteris de l'edició. Amb tot, l'edició crítica en si s'ha mogut a la secció d'annexos, davant les restriccions d'extensió d'un Treball de Fi de Grau.

Aleshores, el lector d'aquest document es trobarà amb una edició crítica de la poesia completa de Joan Terrer, un autor del segle XVII del qual sabíem ben poques coses. Així, el lector es trobarà un autor que s'emmarca dins de les tendències literàries del moment. Per tant, aquest treball és un esforç més de dignificació de la literatura catalana del Barroc.

[fn:1] /Alcaid/ és un mot provinent de l'àrab que a l'època de Terrer indicava el senyoriu sobre un castell.
[fn:2] «\hyperref[poem:XI]{Un casament vergonyant}» a citet:Rossich1979, «\hyperref[poem:XII]{Una cara, un cel, dos sols}» a citet:Rossich1985, i «\hyperref[poem:II]{Quan apar que, ja cansat}» a citet:Rossich2006.
